# Generated by Django 4.1 on 2022-08-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('comissao', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('conf', 'CONFIRMADO'), ('pen', 'PENDENTE'), ('agua', 'AGUARDANDO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('preco', models.CharField(blank=True, max_length=20, null=True)),
                ('duracao', models.CharField(blank=True, max_length=20, null=True)),
                ('comissao', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/imagens/%d/%m/%Y/')),
            ],
        ),
    ]
