# Generated by Django 4.1 on 2022-08-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.BooleanField(default=True)),
                ('terca', models.BooleanField(default=True)),
                ('quarta', models.BooleanField(default=True)),
                ('quinta', models.BooleanField(default=True)),
                ('sexta', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=True)),
                ('domingo', models.BooleanField(default=True)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.colaborador')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico')),
            ],
        ),
    ]
