# Generated by Django 4.1 on 2022-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
